is_debug: false
project_name: squirrel_backend
api_string: /api
secret_key: SECRET_KEY
api_key: API_KEY
access_token_expire_minutes: 10080  # 7 days
password_length: 12
backend_cors_origins: [http://localhost:5050/]

redis_host: redis
redis_port: 6379
