version: "3.8"

services:

  db:
    image: postgres:14.3
    env_file: .env
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    env_file: .env
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  web:
    build:
      context: .
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app/
    ports:
      - "${DOCKER_EXPOSE_PORT:-8001}:${FASTAPI_PORT:-8001}"
    command: uvicorn app.main:app --host 0.0.0.0 --port "${FASTAPI_PORT:-8001}"

  redis:
    image: redis:5.0
    restart: unless-stopped
    volumes:
      - ./.docker/redis-data:/data

  scheduler:
    build:
      context: .
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app/
    command: python app/scheduler.py

  # scanner:
  #   build:
  #     context: .
  #   restart: always
  #   env_file: .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./:/app/
  #   command: python app/services/scanner/start.pyp